### ISSUE TITLE
[DOC] Tutorial refinement

### ISSUE THREAD

**Issue by slumnitz** [BioPAL/BioPAL#28]
* The setup AGB Processor section is missing a description of parameters int he input and configuration parameter section, i.e.:
    * output_specification section:
    * dataset_query section:
    * ground_cancellation section:
    * estimate_agb section:

**Comment by emanuelegiorgi** [comment]
Thank you for the feedback, description is actually there, the problem is the indentation which is misleading.
It can be corrected, within next pull request.
